### PR TITLE
Fixed issue 144. Added nom_res_str to correctly capture intent of nom…

### PR DESCRIPTION
**Pull request by michaelleerilee**
…_res=None. Propagated changes through tests and some granule readers. Added set_nom_res() method to base Granule class.

Ref. #144

### CODE REVIEW

**Comment by michaelleerilee** [comment]
@NiklasPhabian We should bump version and create a release if this update is acceptable.

**Comment by michaelleerilee** [comment]
Note I found and corrected a bunch of errors when running pytest from code not updated since we started adding nom_res to variable names.

**Comment by michaelleerilee** [comment]
I'm getting a clean pytest locally, but pytest is only finding 95 items, not 96.

**Comment by NiklasPhabian** [comment]
by clean pytest, do you mean passing all tests? That would be curious because the GH actions and my local fails two tests. Both possibly caused by pandas>=2.0.0

**Comment by NiklasPhabian** [comment]
uuuf. Indeed, this was caused by pandas. Now unfortunately, pickled dataframes are not compatible between versions. I.e. we would have to re-pod data if we switched to pandas>=2.0.

**Comment by michaelleerilee** [comment]
Is there a path for reading pickles at one version and writing to a new version?

**Comment by NiklasPhabian** [comment]
> I'm getting a clean pytest locally, but pytest is only finding 95 items, not 96.
we had been skipping one of the examples

**Comment by NiklasPhabian** [comment]
@michaelleerilee @mbauer288 can you verify that my edits do not break your usecases?

**Pull request merged**
