### PR TITLE
Modifications for DYAMONDv2 podding.

### PR DESCRIPTION
**Pull request by NiklasPhabian**
Modification of IMERG for podding DYAMONDv2 data from Jiun-Dar.

### CODE REVIEW

**Comment by mbauer288** [comment]
This is for the PMOD artificial IMERG precip features dataset. Needed by STAREPodder

**Comment by NiklasPhabian** [comment]
ok. The issue breaking the test is fixed. @mbauer288, in an ideal world, we'd like to have a test with any of those feature additions. Also, we really don't want any verbose flags and print statements making it into master. 
We should see if we should move towards including logging into starepandas though
https://docs.python.org/3/howto/logging.html

**Comment by NiklasPhabian** [comment]
Also wondering. `read_timestamps()` and `read_latlon()` is not implemented for L3IMERG, right? I.e. we cannot read imerg granules as of now

**Comment by NiklasPhabian** [comment]
oh; also `read_data()` is not implemented! for neither dyamondv2 nor imerg

**Comment by NiklasPhabian** [comment]
OK. So this passes the test now. But we cannot read IMERG and neither diamondv2 with this. We should probably 
- move things from https://github.com/SpatioTemporal/STAREpodder/tree/main/src/STAREpodder/cfg to STAREPandas
- write two simple tests to verify we indeed can read imerg

**Pull request merged**
